# Generated by Django 5.2.17 on 2026-09-13 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dechets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCollecte',
            fields=[
                ('idPoint', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('heureOuverture', models.CharField(max_length=5)),
                ('heureFermeture', models.CharField(max_length=5)),
                ('dechetsAcceptes', models.ManyToManyField(related_name='pointsCollecte', to='dechets.typedechet')),
                ('gerePar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointsGeres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
