# Generated by Django 5.2.17 on 2026-09-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0001_initial'),
        ('collecteurs', '0001_initial'),
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('idCollecte', models.AutoField(primary_key=True, serialize=False)),
                ('datePlanifiee', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('dateRealisation', models.DateTimeField(blank=True, null=True)),
                ('quantiteRecuperee', models.FloatField(blank=True, null=True)),
                ('idCollecteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes', to='collecteurs.collecteur')),
                ('idDemande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes', to='demandes.demandecollecte')),
                ('idPoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes', to='collecte.pointcollecte')),
            ],
        ),
    ]
