# Generated by Django 5.2.17 on 2026-09-24 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collecteurs', '0001_initial'),
        ('dechets', '0004_prixdechet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteDechet',
            fields=[
                ('idVente', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.FloatField()),
                ('prixPaye', models.FloatField()),
                ('methodePaiement', models.CharField(blank=True, max_length=50)),
                ('statutPaiement', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('referencePaiement', models.CharField(blank=True, max_length=100)),
                ('dateVente', models.DateTimeField(auto_now_add=True)),
                ('idCollecteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='collecteurs.collecteur')),
                ('idTypeDechet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='dechets.typedechet')),
                ('idUtilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
