# Generated by Django 5.2.17 on 2026-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventedechet',
            name='tokenPayDunya',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
