# Generated by Django 5.2.17 on 2026-09-24 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collecteur',
            fields=[
                ('idCollecteur', models.AutoField(primary_key=True, serialize=False)),
                ('nomEntreprise', models.CharField(blank=True, max_length=150)),
                ('telephoneProfessionnel', models.CharField(blank=True, max_length=20)),
                ('zoneIntervention', models.CharField(blank=True, max_length=150)),
                ('statutValidation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('dateInscription', models.DateTimeField(auto_now_add=True)),
                ('idUtilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collecteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AbonnementCollecteur',
            fields=[
                ('idAbonnement', models.AutoField(primary_key=True, serialize=False)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('statutPaiement', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('methodePaiement', models.CharField(blank=True, max_length=50)),
                ('montant', models.FloatField()),
                ('idCollecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='collecteurs.collecteur')),
            ],
        ),
    ]
