# Generated by Django 5.2.17 on 2026-09-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementcollecteur',
            name='plan',
            field=models.CharField(choices=[('essentiel', 'Essentiel'), ('professionnel', 'Professionnel'), ('entreprise', 'Entreprise')], default='essentiel', max_length=20),
        ),
        migrations.AddField(
            model_name='abonnementcollecteur',
            name='referencePaiement',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='abonnementcollecteur',
            name='tokenPayDunya',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
