# Generated by Django 5.2.17 on 2026-09-24 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dechets', '0004_prixdechet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCollecte',
            fields=[
                ('idDemande', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.FloatField()),
                ('typeDemande', models.CharField(choices=[('ramassage', 'Ramassage à domicile'), ('depot', 'Dépôt en point de collecte')], default='ramassage', max_length=20)),
                ('prixPropose', models.FloatField(blank=True, null=True)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dateDemande', models.DateTimeField(auto_now_add=True)),
                ('dateSouhaitee', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('idTypeDechet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='dechets.typedechet')),
                ('idUtilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
