# Generated by Django 5.2.17 on 2026-09-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandecollecte',
            name='adresse',
        ),
        migrations.AddField(
            model_name='demandecollecte',
            name='quartier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
