# Generated by Django 5.2.17 on 2026-09-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_remove_demandecollecte_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecollecte',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandecollecte',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
