# Generated by Django 5.2.17 on 2026-09-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecteurs', '0001_initial'),
        ('demandes', '0003_alter_demandecollecte_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecollecte',
            name='collecteurAttribue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandesAttribuees', to='collecteurs.collecteur'),
        ),
    ]
