# Generated by Django 5.2.17 on 2026-09-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecteurs', '0002_abonnementcollecteur_plan_and_more'),
        ('demandes', '0004_demandecollecte_collecteurattribue'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecollecte',
            name='refuseurs',
            field=models.ManyToManyField(blank=True, related_name='demandesRefusees', to='collecteurs.collecteur'),
        ),
    ]
