# Generated by Django 5.2.17 on 2026-09-13 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dechets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanDechet',
            fields=[
                ('idScanDechet', models.AutoField(primary_key=True, serialize=False)),
                ('dateScan', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='scans/')),
                ('idTypeDechet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='dechets.typedechet')),
                ('idUtilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('idAnalyse', models.AutoField(primary_key=True, serialize=False)),
                ('resultat', models.CharField(max_length=100)),
                ('scoreConfiance', models.FloatField()),
                ('dateAnalyse', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyseIA', to='scans.scandechet')),
            ],
        ),
    ]
