# Generated by Django 5.2.17 on 2026-09-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scandechet',
            old_name='idScanDechet',
            new_name='idScan',
        ),
        migrations.RenameField(
            model_name='scandechet',
            old_name='photo',
            new_name='photoUrl',
        ),
    ]
