# Generated by Django 5.2.17 on 2026-09-14 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dechets', '0001_initial'),
        ('scans', '0002_rename_idscandechet_scandechet_idscan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyseia',
            old_name='scan',
            new_name='idScan',
        ),
        migrations.RenameField(
            model_name='scandechet',
            old_name='photoUrl',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='scandechet',
            name='idTypeDechet',
        ),
        migrations.AddField(
            model_name='analyseia',
            name='idTypeDechet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='dechets.typedechet'),
        ),
    ]
