# Generated by Django 5.2.17 on 2026-09-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_rename_scan_analyseia_idscan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scandechet',
            old_name='photo',
            new_name='photoUrl',
        ),
    ]
