# Generated by Django 5.2.17 on 2026-09-18 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dechets', '0003_nettoyer_referentiel_dechets'),
        ('scans', '0004_rename_photo_scandechet_photourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyseia',
            name='idTypeDechet',
        ),
        migrations.CreateModel(
            name='DetectionIA',
            fields=[
                ('idDetection', models.AutoField(primary_key=True, serialize=False)),
                ('objet', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('confiance', models.FloatField()),
                ('idAnalyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='scans.analyseia')),
                ('idTypeDechet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='dechets.typedechet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idAnalyse', 'idTypeDechet'), name='unique_type_dechet_par_analyse')],
            },
        ),
    ]
