# Generated by Django 5.2.17 on 2026-09-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_remove_analyseia_idtypedechet_detectionia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyseia',
            name='resultat',
        ),
        migrations.RemoveField(
            model_name='analyseia',
            name='scoreConfiance',
        ),
    ]
