# Generated by Django 5.2.17 on 2026-09-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_remove_analyseia_resultat_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detectionia',
            name='unique_type_dechet_par_analyse',
        ),
        migrations.RemoveField(
            model_name='detectionia',
            name='quantite',
        ),
    ]
