# Generated by Django 5.2.17 on 2026-09-13 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDechet',
            fields=[
                ('idTypeDechet', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConseilTri',
            fields=[
                ('idConseil', models.AutoField(primary_key=True, serialize=False)),
                ('consigne', models.TextField()),
                ('idTypeDechet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conseil', to='dechets.typedechet')),
            ],
        ),
    ]
