# Generated by Django 5.2.17 on 2026-09-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dechets', '0003_nettoyer_referentiel_dechets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixDechet',
            fields=[
                ('idPrix', models.AutoField(primary_key=True, serialize=False)),
                ('prixParKg', models.FloatField()),
                ('commission', models.FloatField()),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('idTypeDechet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='dechets.typedechet')),
            ],
        ),
    ]
